/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData bookmark = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData city = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData country = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData editpen = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refer = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reportflag = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData risingstar = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shareto = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volumeup = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
